== Compilateur

Le compilateur est divisé en deux parties : le parseur et le superviseur.

Ces deux parties collaborent étroitement pour permettre d'obtenir un automate à partir d'un langage d'entrée : CAL.


=== Parseur

Le parseur est la partie du compilateur qui va s'occuper de créer un descripteur à partir du de la représentation textuelle.
Le descripteur est une structure de données contenant toutes les informations permettant la création d'un automate lorqu'il est passé au modèle.
Cette création s'accompagne d'un autre descripteur totalement symétrique contenant la position dans le texte des différentes données.
Dans le but de pouvoir traiter le langage, nous avons écrit sa grammaire afin de créer un parseur.

La création du parseur s'est faite à l'aide de PEGjs, un outil permettant à partir d'une grammaire de créer un parseur. Il prend en entrée une grammaire dont la syntaxe était très proche de celle vue en théorie des langages et donnait un parseur utilisable dans du code Javascript.
Nous pouvons aussi associer à chaque régle de la grammaire, un bloc de code Javascript permettant ainsi de créer le descripteur sous la forme voulue directement dans la grammaire.

La gestion des erreurs syntaxiques est faite que dans le parseur qui renvoie alors, au lieu d'un descripteur, une erreur qui sera traité par le superviseur.

=== Superviseur 

Le superviseur est en charge de vérifier que toutes les étapes de la compilation se déroule sans erreur et de permettre le passage du descripteur rendu par le parseur au modèle.
C'est lui qui va à chaque étape de la compilation traiter les différentes erreurs ayant pu survenir telles que les erreurs syntaxiques renvoyées par le parseur et les erreurs sémantiques renvoyées par le modéle.
Il est aussi en charge de vérifier certaines erreurs sur le descripteur afin de le rendre propre avant d'alimenter le modèle.

=== Bénéfice de la séparation

==== Choix du langage d'entrée
    
Le fait d'avoir spécifié un protocole permet de se passer du parseur fourni avec l'application et d'utiliser un autre langage pour peu que l'on obtienne un descripteur respectant la protocole.

==== Lisibilité du code de la grammaire

Le modèle n'étant alimenté que par l'intermédiaire du superviseur, le parseur n'est en charge que de la création du descripteur, cela rend donc son code plus lisible.
En effet, le code concernant l'alimentation du modèle n'y intervient pas et une seule tâche est laissée au parseur.

==== Plusieurs formats de sérialisation

Le protocole étant indépendant du parseur, il est tout à fait possible de passer un descripteur non créé à partir du langage. Par exemple, un descripteur écrit en JSON.
