== Compilateur

Le compilateur permet d'obtenir un automate à partir d'un langage d'entrée : CAL.

La compilation se décompose en 3 étapes. Elles sont toutes mises en relation par un module appelé le superviseur.

=== Parseur

Le parseur est la partie du compilateur qui s'occupe de l'analyse lexicale et syntaxique de la représentation textuelle dans le langage CAL.
Il retourne ce que nous appelons un descripteur, c'est-à-dire une structure de données formée des informations contenues dans la représentation textuelle.

Simultanément, le parseur produit et renvoit un second descripteur symétrique au premier.
Au lieu de contenir les données associées aux tokens lus par le parseur,
ce second descripteur fournit la position de ces tokens.

La création du parseur s'est faite à partir de sa grammaire à l'aide de PEGjs, une bibliothèque Javascript semblable à Lex/Bison.
La syntaxe employée par PEGjs pour définir une grammaire est très proche de celle abordée en théorie des langages.

A chaque régle de la grammaire peut être associé un bloc de code Javascript permettant ainsi de créer le descripteur sous la forme voulue.

Si une erreur syntaxique survient, le parseur la renvoit au lieu du descripteur.
Cette erreur est capturée par le compilateur qui la renvoit à son tour.

=== Inférence 

// Une phrase trop longue et trop abstraite.
L'inférence est l'étape consistant à compléter les informations concernant les états et les symboles dans le descripteur en utilisant les informations présentes dans les transitions.
Cette étape est réalisé par le superviseur. Le descripteur ainsi complété est alor passé au modèle.

=== Appel au modèle 

L'appel au modèle est l'étape qui consiste à passer du descripteur à un automate.
Le constructeur d'automate exposé par le modèle prend comme paramétre un descripteur. Si celui-ci est bien spécifié, une instance est renvoyée.
En cas d'erreur, le constructeur renvoit une exception. Le superviseur va associer cette exception à la position du token ayant causé l'erreur
grâce au second descripteur produit par le parseur. Il est ainsi possible de localiser les erreurs sémantiques aussi bien que les erreurs syntaxiques.

=== Protocole

Plusieurs raisons nous aménent à utiliser un descripteur plutôt que de directement appeler les fonctions du modèle dans le parseur.

D'une part, cela assouplit la relation entre le langage et le modèle.
On peut tout à fait changer la syntaxe de CAL ; en effet la présence d'un protocole assure que le modèle est capable de prendre en compte n'importe quel descripteur le respectant.

De plus, le code présent dans la grammaire reste aussi simple que possible. Il n'est dédié qu'à une tâche : la création du descripteur.
Auncun code interagissant avec l'exterieur n'est présent, facilitant ainsi la lecture et la compréhension.

