== Compilateur

Le compilateur permet d'obtenir un automate à partir d'un langage d'entrée : CAL.

Le compilation se décompose en 4 étapes.

=== Parseur

Le parseur est la partie du compilateur qui s'occupe de l'analyse lexicale et syntaxe de la représentation textuelle dans le langage CAL.
Il retourne ce que nous appelons un description, c'est-à-dire une structure de données formée des informations contenues dans la représentation textuelle.

Simultanément, le parseur produit et renvoit un second descripteur symétrique au premier.
Au lieu de contenir les données associées aux tokens lus par le parseur,
ce second descripteur fournit la position de ces tokens.

La création du parseur s'est faire à partir de sa grammaire à l'aide de PEGjs, une bibliothèque Javascript semblable à Lex/Bison.
La syntaxe employée par PEGjs pour définir une grammaire est très proche de celle abordée en théorie des langages.

A chaque régle de la grammaire peut être associé un bloc de code Javascript permettant ainsi de créer le descripteur sous la forme voulue.

Si une erreur syntaxique survient, le parseur la renvoit au lieu du descripteur.
Cette erreur est capturée par le compilateur qui la renvoit à son tour.

=== Superviseur 

Le superviseur est en charge de vérifier que toutes les étapes de la compilation se déroule sans erreur et de permettre le passage du descripteur rendu par le parseur au modèle.
C'est lui qui va à chaque étape de la compilation traiter les différentes erreurs ayant pu survenir telles que les erreurs syntaxiques renvoyées par le parseur et les erreurs sémantiques renvoyées par le modéle.
Il est aussi en charge de vérifier certaines erreurs sur le descripteur afin de le rendre propre avant d'alimenter le modèle.

=== Bénéfice de la séparation

==== Choix du langage d'entrée
    
Le fait d'avoir spécifié un protocole permet de se passer du parseur fourni avec l'application et d'utiliser un autre langage pour peu que l'on obtienne un descripteur respectant la protocole.

==== Lisibilité du code de la grammaire

Le modèle n'étant alimenté que par l'intermédiaire du superviseur, le parseur n'est en charge que de la création du descripteur, cela rend donc son code plus lisible.
En effet, le code concernant l'alimentation du modèle n'y intervient pas et une seule tâche est laissée au parseur.

==== Plusieurs formats de sérialisation

Le protocole étant indépendant du parseur, il est tout à fait possible de passer un descripteur non créé à partir du langage. Par exemple, un descripteur écrit en JSON.
