== Conclusion

L'issue de ce projet est une application Web côté client capable de dessiner
un automate en SVG à partir d'une représentation textuelle.
Cette représentation textuelle est défini à l'aide d'un nouveau langage
appelé CAL, pour *Concise Automaton Language*.

Ce projet peut servir de point de départ pour une application plus poussée intégrant par exemple l'édition graphique.
Cette expérience nous a été très profitable, tant au niveau technique qu'au niveau organisationnel.
En effet nous avons pu employer nous exercer à des méthodes et à des outils de collaboration, comme Git.
Non seulement le sujet porte sur la représentation d'objets issus de la théorie
des langages, mais en plus nous avons fait usage de cette même théorie via
la définition du langage CAL et l'implémentation de son compilateur.
Nos connaissances dans le domaine ont donc été bien consolidées.

Nous retiendrons de nos succès et de nos difficultés de nombreux enseignements.
D'une part, nous avons noté l'importance d'une bonne communication,
qu'elle soit entre les membres de l'équipe, avec le tuteur ou avec le jury.
D'autre part, la planification sérieuse apparait comme une nécessiter. Le
fait de fixer des objetifs modeste dans des délais courts nous aurait permis
de conserver une motivation constante tout au long du projet.
