== Introduction

La théorie des automates fournit les outils de formalisation des machines de
calcul et trouve de nombreuses applications, notamment en théorie
des langages. Enseignants, chercheurs et étudiants du domaine doivent
fréquemment manipuler ces objets dont l'écriture mathématique est pour le moins
fastidieuse. Il est plus facile, à des fins de compréhension et de communication
 de représenter les automates sous forme de dessins.
Si un tel dessin présente toutes les informations nécessaires à quiconque
le regarde, il ne présente pas le même formalisme qu'une définition précise de l'objet.

Un logiciel pourrait réconcilier ces deux représentations - l'une mathématique,
l'autre graphique - en proposant de dessiner un automate à partir d'une
description, ou en produisant une description à partir d'un dessin.

Nous avons entrepris la réalisation d'un tel logiciel à la demande et sous
la supervision de M. Nicart, enseignant-chercheur à l'université de Rouen.
L'objectif est de définir un langage capable de décrire un automate, puis de
fournir un compilateur sur ce langage à même de produire le dessin correspondant.

Des solutions logicielles traitant des automates existent déjà, mais ce projet
fait un usage exclusif des technologies Web.
Proposer ces fonctionnalités directement dans le navigateur offre la garantie
d'un logiciel portable, que le développeur peut aisément déployer et dont
l'utilisateur peut facilement avoir accés. L'application tient d'ailleurs son
nom du format de dessin vectoriel SVG utilisable directement dans une page Web.

Enfin, le département informatique de l'université de Rouen est interessé par
un retour d'expérience afin d'évaluer la maturité des technologies Web pour
ce genre d'entreprise. Ce projet sert alors également de preuve de concept.
