== Outils 

Quatre outils majeurs ont facilité la communication au sein de l'équipe
et la modularité du code. Ils sont les suivants.

npm ::
  Le _node package manager_ est un outil qui permet d'installer différents paquetages Javascript.
  La gestion des dépendances est automatique et permet donc un dépoiement facilité.
  Par conséquent, tous les membres de l'équipe disposaient du même environnement de développement.

Brunch ::
  Brunch prépare des sources déployables à partir des sources éditées.
  Cet un moteur de production adapté aux applications Web clients.
  Les sources Javascript sont enrobées d'une fonction anonyme puis concaténées dans un seul fichier cible.
  Le code est ainsi modularisé, donc aisément réutilisable, tout en étant facile à déployer.
  De plus, Brunch orchestre l'exécution de différents _linters_ et transpileurs.
  Nous avons ainsi pu utiliser le dernier standard Javascript, ES2015, puisque les sources étaient ensuite traduites dans une version
  compatible avec le plus grand nombre de navigateurs.

Git ::
  Git est un système de gestion de version.
  Ses branches faciles d'emploi nous ont permis de travailler simultanément sur la même base de code
  sans altérer le travail des autres.
  Partager ce code en ligne fût très facile grâce à Github, un service d'hebergement publique de dépots Git.

Google Hangouts ::
  Google Hangouts est un logiciel de voix sur IP disposant d'une fonctionnalité de partage d'écran.
  Celle-ci nous a permis d'étendre nos plages horaires de travail car nous pouvions collaborer en direct indépendamment des horaires d'ouverture de la faculté.
  Partager son code via cette fonctionnalité est aussi un avantage lors du débogage car il permet d'apporter très rapidement un oeil neuf sur notre code.


== Equipes

L'architecture du projet a très vite amené à une séparation en sous-équipes de 2 personnes.
La première composée d'Achraf et de Thibaut était en charge du parseur et de la gestion des erreurs.
La seconde équipe composée de Yacine et de Tom s'occupait du modèle et du dessin.
Cette séparation a pu s'opérer très facilement. D'une part grâce à nos outils ;
d'autre part grâce au protocole qui fût défini en amont par l'èquipe entière.


== Rencontres

Dès le début du projet, nous avons planifié des réunions hebdomadiares.
Ces rencontes permettaient de faire le bilan de la semaine passée.
Nous fixions ensuite les objectifs de la semaine suivante selon ce qui avait déjà été fait.
C'était aussi l'occasion de réfléchir ensemble à des choix concernant l'ensemble de l'application tel que le protocole.
Enfin cela permettait de préparer la réunion avec notre tuteur, M. Nicart.
Celle-ci nous donnait l'occasion de faire un retour sur notre avancement et d'obtenir l'avis du tuteur sur les points que nous allions aborder.
C'était aussi un moyen de réviser les objectifs et de se concentrer sur l'essentiel.
Nous avions aussi mis en place l'application sur un site accessible facilement afin d'obtenir un suivi optimal.
